export const BlogData = [
  {
    id: 1,
    img: "https://source.unsplash.com/random",
    date: "July 23, 2023",
    postedBy: "Abdullah Mamun",
    title: "Search For House Rent in a Property For Rent end.",
  },
  {
    id: 2,
    img: "https://source.unsplash.com/random",
    date: "August 5, 2023",
    postedBy: "Emma Smith",
    title: "10 Tips for a Successful Home Renovation Project",
  },
  {
    id: 3,
    img: "https://source.unsplash.com/random",
    date: "September 12, 2023",
    postedBy: "John Doe",
    title: "The Art of Interior Design: Creating Your Dream Home",
  },
  {
    id: 4,
    img: "https://source.unsplash.com/random",
    date: "October 8, 2023",
    postedBy: "Maria Garcia",
    title: "How to Choose the Right Neighborhood for Your Family",
  },
  {
    id: 5,
    img: "https://source.unsplash.com/random",
    date: "November 16, 2023",
    postedBy: "David Brown",
    title: "Green Living: Eco-Friendly Home Improvement Ideas",
  },
  {
    id: 6,
    img: "https://source.unsplash.com/random",
    date: "December 2, 2023",
    postedBy: "Sophia Johnson",
    title: "The Ultimate Guide to Buying Your First Home",
  },
  {
    id: 7,
    img: "https://source.unsplash.com/random",
    date: "January 9, 2024",
    postedBy: "Michael Wilson",
    title: "Real Estate Market Trends: What to Expect in 2024",
  },
  {
    id: 8,
    img: "https://source.unsplash.com/random",
    date: "November 16, 2023",
    postedBy: "David Brown",
    title: "Green Living: Eco-Friendly Home Improvement Ideas",
  },
  {
    id: 9,
    img: "https://source.unsplash.com/random",
    date: "December 2, 2023",
    postedBy: "Sophia Johnson",
    title: "The Ultimate Guide to Buying Your First Home",
  },
  {
    id: 10,
    img: "https://source.unsplash.com/random",
    date: "January 9, 2024",
    postedBy: "Michael Wilson",
    title: "Real Estate Market Trends: What to Expect in 2024",
  },
];
